### ISSUE TITLE
Change actuator port from 8080 to 8090 and implement kubernetes backend config

### ISSUE THREAD

**Issue by mirioeggmann** [yb-hackathon-code-butcher/codebase#78]
Currently actuator runs on the same port as the rest api. It would be great if we can change it to a different port.

### Example of a backend config and how to annotate it in the service
```yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: haubzit-backend-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 8090
    type: HTTP
    requestPath: /actuator/health
```
```yaml
apiVersion: v1
kind: Service
metadata:
  name: haubzit-backend
  labels:
    appl: haubzit-backend
  annotations:
    cloud.google.com/backend-config: '{"ports": {"actuator":"haubzit-backend-backendconfig"}}'
spec:
  selector:
    appl: haubzit-backend
  type: NodePort
  ports:
    - name: actuator
      protocol: TCP
      port: 8090
      targetPort: actuator
```
```yaml
# Add the following to the deployment container:
readinessProbe:
    httpGet:
      path: /actuator/health
      port: actuator
    initialDelaySeconds: 5
    periodSeconds: 5

```
### In application yaml add:
```yaml
management:
  server:
    port: 8090
```
