### ISSUE TITLE
Configure secrets in gke for deployments

### ISSUE THREAD

**Issue by mirioeggmann** [yb-hackathon-code-butcher/codebase#79]
```yaml
- name: APPL_DATASOURCE_USERNAME
  value: haubzit
- name: APPL_DATASOURCE_PASSWORD
  value: haubzit
```
```yaml
- name: POSTGRES_USER
  value: haubzit
- name: POSTGRES_PASSWORD
  value: haubzit
```
